version: '3'
services:
  node:
    build: .
    ports: 
      - "5000:3000"
    expose: 
      - "3000"
    links: 
      - mysql 
    depends_on: 
      - mysql
  mysql:
    image: "mysql/mysql-server" 
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: wnddkd1204
      MYSQL_DATABASE: my_db
      MYSQL_USER: root
      MYSQL_PASSWORD: wnddkd1204
    expose: 
      - "3306"